import { chromium } from 'playwright';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),out=path.join(root,'public/art/woodland-shrine'),ev=path.join(root,'art/verification/woodland-shrine'),manifest=JSON.parse(fs.readFileSync(path.join(out,'manifest.json')));
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://x').pathname);const f=path.join(out,pathname==='/'?'index.html':pathname);if(!f.startsWith(out)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.glb':'model/gltf-binary','.jpg':'image/jpeg','.png':'image/png'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu']});let report={passed:false,devices:[],assetHttpHashes:[]};
try{
 for(const a of manifest.assets){const response=await fetch(url+a.file);assert.equal(response.status,200);const bytes=Buffer.from(await response.arrayBuffer());assert.equal(createHash('sha256').update(bytes).digest('hex'),a.sha256);report.assetHttpHashes.push({id:a.id,passed:true,sha256:a.sha256});}
 for(const mobile of [false,true]){
  const name=mobile?'mobile':'desktop',context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1050},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:1});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await page.goto(url);try{await page.waitForFunction(()=>window.kitQA?.active==='mossveil-sanctuary'&&window.kitQA.frames>5);}catch(e){console.log('STARTUP ERRORS',errors,await page.locator('body').innerText());throw e;}assert.equal(await page.locator('canvas').count(),1);
  const gl=await page.evaluate(()=>{const c=document.querySelector('canvas'),gl=c.getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');return ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unknown';});
  const loaded=[];for(const a of manifest.assets){await page.locator(`[data-id="${a.id}"]`).click();await page.waitForFunction(id=>window.kitQA.active===id,a.id);assert.equal(await page.locator('#title').textContent(),a.name);loaded.push(a.id);if(a.id==='sunleaf-altar'){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(ev,`${name}-altar-detail.png`),fullPage:true});}}
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(ev,`${name}-assembled-sanctuary.png`),fullPage:true});await page.locator('#filter').selectOption('Ruined masonry');assert.equal(await page.locator('.asset').count(),2);await page.locator('[data-id="broken-sun-arch"]').click();await page.waitForFunction(()=>window.kitQA.active==='broken-sun-arch');await page.locator('#spin').click();assert.equal(await page.locator('#spin').getAttribute('aria-pressed'),'true');await page.locator('#spin').click();assert.equal(await page.locator('#spin').getAttribute('aria-pressed'),'false');await page.locator('#reset').click();await page.locator('#stage').scrollIntoViewIfNeeded();
  const beforeDrag=await page.evaluate(()=>window.kitQA.camera);const stage=await page.locator('#stage').boundingBox();await page.mouse.move(stage.x+stage.width*.48,stage.y+stage.height*.4);await page.mouse.down();await page.mouse.move(stage.x+stage.width*.59,stage.y+stage.height*.45,{steps:10});await page.mouse.up();await page.waitForFunction(before=>window.kitQA.camera.some((v,i)=>Math.abs(v-before[i])>.01),beforeDrag);await page.locator('#reset').click();
  if(mobile){const beforeTouch=await page.evaluate(()=>window.kitQA.camera);const cdp=await context.newCDPSession(page);const b=await page.locator('canvas').boundingBox();const x=b.x+b.width*.45,y=b.y+b.height*.38;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+45,y:y+20}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(before=>window.kitQA.camera.some((v,i)=>Math.abs(v-before[i])>.01),beforeTouch);await page.locator('#reset').click();}
  const download=await Promise.all([page.waitForEvent('download'),page.locator('#download').click()]);assert.equal(download[0].suggestedFilename(),'broken-sun-arch.glb');const downloadedBytes=fs.readFileSync(await download[0].path());assert.equal(downloadedBytes.readUInt32LE(0),0x46546c67);assert.equal(createHash('sha256').update(downloadedBytes).digest('hex'),manifest.assets.find(a=>a.id==='broken-sun-arch').sha256);
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(ev,`${name}-gallery.png`),fullPage:true});await page.locator('#filter').selectOption('Sacred details');await page.locator('[data-id="dry-offering-basin"]').click();await page.waitForFunction(()=>window.kitQA.active==='dry-offering-basin');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(ev,`${name}-landmarks.png`),fullPage:true});
  await page.locator('#filter').selectOption('Woodland relics');assert.equal(await page.locator('.asset').count(),2);const state=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,qa:window.kitQA}));assert.equal(state.overflow,false);assert.equal(state.qa.loaded.length,9);assert.deepEqual(state.qa.errors,[]);assert.deepEqual(errors,[]);report.devices.push({name,passed:true,renderer:gl,loaded,filter:true,rotationToggle:true,pointerDrag:true,touchDrag:mobile,reset:true,glbDownload:true,errors,frames:state.qa.frames,horizontalOverflow:false});await context.close();
 }
 report.passed=true;
}finally{fs.writeFileSync(path.join(ev,'browser-verification.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}
console.log(JSON.stringify(report,null,2));
