import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {Box3,Vector3,Matrix4} from 'three';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),out=path.join(root,'public/art/character-reimagined'),ev=path.join(root,'art/verification/character-reimagined');const manifest=JSON.parse(fs.readFileSync(path.join(out,'manifest.json')));
async function load(f){const b=fs.readFileSync(f);return new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}
const results=[];const loaded={};
for(const a of manifest.assets){const buf=fs.readFileSync(path.join(out,a.file));const gltf=await load(path.join(out,a.file));loaded[a.id]=gltf;gltf.scene.updateMatrixWorld(true);const box=new Box3().setFromObject(gltf.scene);assert(Math.abs(box.min.y)<1e-5,a.id+' ground');assert(box.max.y>1.1&&box.max.y<1.3,a.id+' familiar height');assert.equal(gltf.animations.length,0);let triangles=0,vertices=0,meshes=0,materials=new Set();gltf.scene.traverse(o=>{if(!o.isMesh)return;assert(!o.isSkinnedMesh);meshes++;const g=o.geometry,p=g.attributes.position,n=g.index?.count??p.count;vertices+=p.count;triangles+=n/3;assert(g.attributes.normal);materials.add(o.material.name);for(const key of ['position','normal'])for(const v of g.attributes[key].array)assert(Number.isFinite(v),a.id+' finite '+key);for(let i=0;i<n;i+=3){const v=[0,1,2].map(k=>new Vector3().fromBufferAttribute(p,g.index?g.index.getX(i+k):i+k));assert(v[1].sub(v[0]).cross(v[2].sub(v[0])).lengthSq()>1e-18,a.id+' nondegenerate '+o.name);}});const measured={bytes:buf.length,sha256:createHash('sha256').update(buf).digest('hex'),bounds:{min:box.min.toArray(),max:box.max.toArray()},triangles,vertices,meshNodes:meshes,materialCount:materials.size};if(process.argv.includes('--measure'))Object.assign(a,measured);else for(const [k,v]of Object.entries(measured))assert.deepEqual(a[k],v);if(a.kind==='candidate'){for(const suffix of ['head','arm_L','arm_R','nose','thumb_-1','thumb_1','strap'])assert(gltf.scene.getObjectByName(a.id+'_'+suffix),a.id+' named '+suffix);const shoulder=gltf.scene.getObjectByName(a.id+'_arm_R');assert(Math.abs(shoulder.position.x-.32)<1e-5);assert(Math.abs(shoulder.position.y-.52)<1e-5);const hand=gltf.scene.getObjectByName(a.id+'_palm_1'),before=hand.getWorldPosition(new Vector3());shoulder.rotation.x-=.8;gltf.scene.updateMatrixWorld(true);const after=hand.getWorldPosition(new Vector3());assert(after.distanceTo(before)>.1);shoulder.rotation.x+=.8;gltf.scene.updateMatrixWorld(true);}results.push({id:a.id,passed:true,...measured});}
// Prove baseline major-body geometry was taken from the actual existing GLB,
// not fabricated from boxes or the older fallback. Compare unique world positions
// after subtracting the documented runtime anchor (no re-sculpting permitted).
const original=await load(path.join(root,'art/blender/character-reimagined/baseline-reference/character.glb'));original.scene.updateMatrixWorld(true);const base=loaded['baseline-current'].scene;const baselineProof=[];
function points(o,anchor){o.updateWorldMatrix(true,false);const p=o.geometry.attributes.position;const points=[];for(let i=0;i<p.count;i++)points.push(new Vector3().fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld).sub(anchor));return points;}
for(const [name,anchor]of Object.entries({head:[0,.88,0],torso:[0,.48,0],leg:[-.11,.19,0],foot:[-.11,.04,.02],hair_cap:[0,1.14,0],belt:[0,.48,-.16]})){const source=original.scene.getObjectByName(name),copy=base.getObjectByName('baseline_'+name+'0');assert(source?.isMesh&&copy?.isMesh,name);const s=points(source,new Vector3()),c=points(copy,new Vector3(...anchor));let max=0;for(const v of c){let best=Infinity;for(const x of s)best=Math.min(best,v.distanceTo(x));max=Math.max(max,best);}assert(max<2e-6,name+' baseline vertex preservation');baselineProof.push({part:name,maximumNearestVertexError:max,passed:true});}
if(process.argv.includes('--measure'))fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');const report={passed:true,loader:'Actual installed Three.js GLTFLoader',assets:results,baselineGeometryProof:baselineProof,scope:'Static geometry, actual rigid arm node transform. No live integration, no performance claim.'};fs.writeFileSync(path.join(ev,'geometry-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
