import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';import {Box3,Vector3,Matrix4} from 'three';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),out=path.join(root,'public/art/character-reimagined'),ev=path.join(root,'art/verification/character-reimagined');const manifest=JSON.parse(fs.readFileSync(path.join(out,'manifest.json')));const results=[],scenes={};
async function parse(file){const b=fs.readFileSync(file);return {b,gltf:await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')};}
for(const asset of manifest.assets){const {b,gltf}=await parse(path.join(out,asset.file));scenes[asset.id]=gltf.scene;gltf.scene.updateMatrixWorld(true);const bounds=new Box3().setFromObject(gltf.scene);let triangles=0,vertices=0,meshes=0;const colors=new Set();
assert(Math.abs(bounds.min.y)<1e-5,asset.id+' ground');assert(bounds.max.y>1.1&&bounds.max.y<1.3,asset.id+' Emberhall height');assert(bounds.max.x-bounds.min.x<.9,asset.id+' silhouette width');assert.equal(gltf.animations.length,0);
gltf.scene.traverse(o=>{if(!o.isMesh)return;meshes++;const g=o.geometry,p=g.attributes.position,n=g.attributes.normal;assert(p&&n);vertices+=p.count;for(const x of [...p.array,...n.array])assert(Number.isFinite(x));const count=g.index?.count??p.count;triangles+=count/3;for(let i=0;i<count;i+=3){const ps=[0,1,2].map(k=>new Vector3().fromBufferAttribute(p,g.index?g.index.getX(i+k):i+k));assert(ps[1].sub(ps[0]).cross(ps[2].sub(ps[0])).lengthSq()>1e-18,asset.id+' triangle area');}for(const m of Array.isArray(o.material)?o.material:[o.material]){assert(!m.map,'no external texture');colors.add(m.color.getHexString());}});
if(asset.kind==='candidate'){for(const part of ['head','arm_L','arm_R'])assert(gltf.scene.getObjectByName(asset.id+'_'+part),'named pivot');assert(colors.size>=10);}
const measured={bytes:b.length,sha256:createHash('sha256').update(b).digest('hex'),vertices,triangles,meshPrimitives:meshes,materialColors:colors.size,bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()}};Object.assign(asset,measured);results.push({id:asset.id,passed:true,...measured});}
// Current baseline body is exact actual GLB geometry, not primitive stand-in.
const {gltf:current}=await parse(path.join(root,'public/art/lanternwood/character.glb'));current.scene.updateMatrixWorld(true);const baseline=scenes['baseline-current'];const proof=[];
for(const [part,at] of Object.entries({head:[0,.88,0],torso:[0,.48,0],leg:[-.11,.19,0],foot:[-.11,.04,.02],hair_cap:[0,1.14,0],belt:[0,.48,-.16]})){
 const old=current.scene.getObjectByName(part),now=baseline.getObjectByName('baseline_'+part+'0');assert(old?.isMesh&&now?.isMesh,part);
 const target=new Vector3(...at),original=[];for(let i=0;i<old.geometry.attributes.position.count;i++)original.push(new Vector3().fromBufferAttribute(old.geometry.attributes.position,i).applyMatrix4(old.matrixWorld).add(target));let maxError=0;const p=now.geometry.attributes.position;for(let i=0;i<p.count;i++){const v=new Vector3().fromBufferAttribute(p,i).applyMatrix4(now.matrixWorld);const error=Math.min(...original.map(o=>o.distanceTo(v)));maxError=Math.max(maxError,error);}assert(maxError<1e-5,part+' unchanged current geometry');proof.push({part,maxNearestVertexError:maxError});}
const base=results[0];for(const a of results.slice(1)){a.heightRatioToCurrent=a.bounds.max[1]/base.bounds.max[1];a.widthRatioToCurrent=(a.bounds.max[0]-a.bounds.min[0])/(base.bounds.max[0]-base.bounds.min[0]);assert(a.heightRatioToCurrent>.9&&a.heightRatioToCurrent<1.1);assert(a.widthRatioToCurrent>.85&&a.widthRatioToCurrent<1.15);}
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2));const report={passed:true,loader:'Actual installed Three.js GLTFLoader',scope:'Static structure and body silhouette; not performance or gameplay acceptance',assets:results,baselineGeometryProof:proof};fs.writeFileSync(path.join(ev,'geometry-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
