import {chromium} from 'playwright';import {start} from './serve.mjs';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),out=path.join(root,'public/art/character-reimagined'),ev=path.join(root,'art/verification/character-reimagined');const manifest=JSON.parse(fs.readFileSync(path.join(out,'manifest.json')));const server=await start();const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu']});const report={passed:false,assetHashes:[],devices:[]};
try{
 for(const a of manifest.assets){const r=await fetch(origin+'/'+a.file);assert.equal(r.status,200);const sha=createHash('sha256').update(Buffer.from(await r.arrayBuffer())).digest('hex');assert.equal(sha,a.sha256);report.assetHashes.push({id:a.id,sha256:sha,passed:true});}
 for(const mobile of [false,true]){
  const name=mobile?'mobile':'desktop';const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1100},deviceScaleFactor:1,isMobile:mobile,hasTouch:mobile});const page=await context.newPage(),errors=[],remote=[];
  await context.route('**/*',route=>{if(!route.request().url().startsWith(origin)&&!route.request().url().startsWith('data:')){remote.push(route.request().url());return route.abort();}return route.continue();});
  page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
  await page.goto(origin);try{await page.waitForFunction(()=>window.characterQA?.frames>8,{},{timeout:30000});}catch(e){console.log('START FAIL',errors,await page.locator('body').innerText());throw e;}
  const gpu=await page.evaluate(()=>{const gl=document.querySelector('canvas').getContext('webgl2'),e=gl.getExtension('WEBGL_debug_renderer_info');return e?gl.getParameter(e.UNMASKED_RENDERER_WEBGL):'unknown';});
  const screenshots=[];
  for(const id of ['rowan','mira','arden']){await page.locator(`[data-id="${id}"]`).click();await page.waitForFunction(id=>window.characterQA.active===id,id);for(const view of ['body','face','game']){await page.locator(`[data-view="${view}"]`).click();await page.waitForFunction(v=>window.characterQA.view===v,view);await page.waitForTimeout(250);await page.locator('#stage').scrollIntoViewIfNeeded();const file=`${name}-${id}-${view}.png`;await page.locator('#stage').screenshot({path:path.join(ev,file)});screenshots.push(file);assert((await page.evaluate(()=>window.characterQA.camera)).every(Number.isFinite));}}
  await page.locator('[data-view="body"]').click();await page.locator('#pose').click();await page.waitForFunction(()=>window.characterQA.pose&&Math.abs(window.characterQA.armRotation[0]+.8)<1e-5);await page.locator('#stage').screenshot({path:path.join(ev,`${name}-arm-study.png`)});await page.locator('#pose').click();
  await page.locator('#spin').click();const before=await page.evaluate(()=>window.characterQA.rotation);await page.waitForFunction(v=>window.characterQA.rotation>v+.02,before);await page.locator('#spin').click();await page.locator('#reset').click();
  await page.locator('#compare').click();assert.equal(await page.evaluate(()=>window.characterQA.compare),false);await page.locator('#compare').click();assert.equal(await page.evaluate(()=>window.characterQA.compare),true);
  await page.locator('#stage').scrollIntoViewIfNeeded();const box=await page.locator('#stage').boundingBox(),initial=await page.evaluate(()=>window.characterQA.camera);await page.mouse.move(box.x+box.width*.5,box.y+box.height*.4);await page.mouse.down();await page.mouse.move(box.x+box.width*.65,box.y+box.height*.5,{steps:8});await page.mouse.up();await page.waitForFunction(v=>window.characterQA.camera.some((n,i)=>Math.abs(n-v[i])>.01),initial);await page.locator('#reset').click();
  if(mobile){await page.locator('#stage').scrollIntoViewIfNeeded();const b=await page.locator('#stage').boundingBox(),old=await page.evaluate(()=>window.characterQA.camera),cdp=await context.newCDPSession(page);const x=b.x+b.width*.5,y=b.y+b.height*.5;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+45,y:y+15}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(v=>window.characterQA.camera.some((n,i)=>Math.abs(n-v[i])>.01),old);await page.locator('#reset').click();}
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#download').click()]);assert.equal(download.suggestedFilename(),'arden.glb');assert.equal(createHash('sha256').update(fs.readFileSync(await download.path())).digest('hex'),manifest.assets.find(a=>a.id==='arden').sha256);
  await page.locator('[data-id="rowan"]').click();await page.locator('#reset').click();await page.waitForTimeout(300);const resetPosition=await page.evaluate(()=>window.characterQA.camera);assert(resetPosition.every((v,i)=>Math.abs(v-[.82,1.35,-2.8][i])<1e-6),'reset clears orbit inertia');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(ev,`${name}-gallery.png`),fullPage:true});const state=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,qa:window.characterQA}));assert(!state.overflow);assert.equal(state.qa.loaded.length,4);assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
  report.devices.push({name,passed:true,gpu,loaded:state.qa.loaded,screenshots,externalRequests:remote,errors,pointerOrbit:true,touchOrbit:mobile,compareToggle:true,rigidArmStudy:true,turntable:true,reset:true,glbDownloadHash:true,horizontalOverflow:false});await context.close();
 }
 report.passed=true;
}finally{fs.writeFileSync(path.join(ev,'browser-verification.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}
console.log(JSON.stringify(report,null,2));
