import test from 'node:test';import assert from 'node:assert/strict';
import {createGroundUpdatePlanner} from '../src/components/game/ground-update-planner.ts';
const request=()=>({tiles:Array.from({length:8},()=>Array.from({length:8},()=>({kind:'grass',h:1}))),span:{x0:0,z0:0,width:8,height:8},dependencies:[{},256,290,{},10,20,true,'srgb-linear']});
const sync=(p,r)=>{const t=p.prepare(r);t.commit();return t.plan;};
test('exact unchanged request skips; kind/height edit patches only dirty tile',()=>{const p=createGroundUpdatePlanner(),r=request();assert.equal(sync(p,r).mode,'full');assert.equal(sync(p,r).mode,'skip');r.tiles[3][4].h=2;assert.deepEqual(sync(p,r),{mode:'patch',dirty:[{tx:4,ty:3}]});r.tiles[3][4].kind='tree';assert.equal(sync(p,r).mode,'patch');});
test('each external dependency invalidates including output arrays and biome anchors',()=>{for(let i=0;i<8;i++){const p=createGroundUpdatePlanner(),r=request();sync(p,r);r.dependencies[i]={changed:true};assert.equal(sync(p,r).mode,'full');}});
test('world tiles and span changes invalidate',()=>{const p=createGroundUpdatePlanner(),r=request();sync(p,r);r.tiles=structuredClone(r.tiles);assert.equal(sync(p,r).mode,'full');r.span.x0=1;assert.equal(sync(p,r).mode,'full');});
test('uncommitted write retries; stale commit rejected',()=>{const p=createGroundUpdatePlanner(),r=request();p.prepare(r);assert.equal(p.prepare(r).plan.mode,'full');const a=p.prepare(r),b=p.prepare(r);a.commit();assert.throws(()=>b.commit(),/Stale/);});
test('large edit falls back to full and missing tile is distinguished',()=>{const p=createGroundUpdatePlanner(1),r=request();sync(p,r);r.tiles[0][0]=undefined;assert.equal(sync(p,r).mode,'patch');r.tiles[0][1].h=3;r.tiles[0][2].h=3;assert.equal(sync(p,r).mode,'full');});
test('invalid/unbounded spans rejected',()=>{const p=createGroundUpdatePlanner(),r=request();for(const width of [0,-1,1.5,1000000])assert.throws(()=>p.prepare({...r,span:{...r.span,width}}),/Invalid/);});
