import { chromium } from 'playwright';
import fs from 'node:fs';
import crypto from 'node:crypto';
const out='plans/integration-browser';fs.mkdirSync(out,{recursive:true});
const results={url:'http://127.0.0.1:8183',checks:[],errors:[],consoleErrors:[],screens:[],fixtures:['Disposable contexts only; native New hall then controlled intro bypass. Storage errors injected on Storage.prototype.setItem; restored before native Retry. Store begin wrapped only to count calls, delegates original.']};
const flush=()=>fs.writeFileSync(`${out}/results.json`,JSON.stringify(results,null,2));
const check=(name,ok,data={})=>{results.checks.push({name,ok,...data});flush();console.log(name,ok,JSON.stringify(data));};
const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11','--enable-gpu']});
try {for(const [name,viewport,mobile] of [['desktop',{width:1280,height:800},false],['portrait',{width:390,height:844},true],['landscape',{width:844,height:390},true]]){
 const context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile});const page=await context.newPage();page.setDefaultTimeout(10000);
 page.on('pageerror',e=>{results.errors.push({name,message:e.message});flush();});page.on('console',m=>{if(m.type()==='error'){results.consoleErrors.push({name,message:m.text()});flush();}});
 const snap=async(s)=>{await page.screenshot({path:`${out}/${name}-${s}.png`});results.screens.push(`${name}-${s}.png`);flush();};
 const activate=async(label)=>{const b=page.getByRole('button',{name:label,exact:true});if(mobile)await b.tap();else await b.click();};
 try{
 await page.goto(`${results.url}/?qa=1`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__ember?.useGame.getState().phase==='title');
 if(name==='desktop'){
 const assets=await page.evaluate(()=>performance.getEntriesByType('resource').map(x=>x.name).filter(x=>/\/assets\/.*\.(js|css)$/.test(x)));
 const hashes=[];for(const u of assets){const bytes=Buffer.from(await (await page.request.get(u)).body());const pathname=new URL(u).pathname;const file=`.vercel/output/static${pathname}`;hashes.push({pathname,match:fs.existsSync(file)&&bytes.equals(fs.readFileSync(file)),sha256:crypto.createHash('sha256').update(bytes).digest('hex'),saveBannerToken:bytes.includes(Buffer.from('Retry save'))});}
 check('served-current-assets',hashes.length>0&&hashes.every(x=>x.match),{assets:hashes});}
 await activate('New hall');await page.waitForFunction(()=>window.__ember.useGame.getState().phase==='intro');await page.evaluate(()=>window.__ember.useGame.setState({phase:'playing'}));await page.waitForTimeout(1400);
 const saved=await page.evaluate(()=>{const s=window.__ember.useGame.getState();s.speed(0);s.saveNow();return localStorage.getItem('emberhall-save-v4');});check(`${name}-disposable-save-created`,!!saved);
 await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Continue',exact:true}).waitFor();
 await page.evaluate(()=>{const g=window.__ember.useGame;const begin=g.getState().begin;window.__beginCalls=0;g.setState({begin:(...args)=>{window.__beginCalls++;return begin(...args);}});});
 for(const cancel of ['Keep my hall','Escape']){await activate('New hall');await page.getByRole('alertdialog').waitFor();if(cancel==='Escape')await page.keyboard.press('Escape');else await activate(cancel);await page.getByRole('button',{name:'New hall',exact:true}).waitFor();const r=await page.evaluate(()=>({bytes:localStorage.getItem('emberhall-save-v4'),calls:window.__beginCalls,focus:document.activeElement?.textContent}));check(`${name}-cancel-${cancel}`,r.bytes===saved&&r.calls===0&&r.focus==='New hall',{sameBytes:r.bytes===saved,calls:r.calls,focus:r.focus});}
 await page.waitForTimeout(550);await activate('New hall');await activate('Erase it and start anew');await page.waitForFunction(()=>window.__ember.useGame.getState().phase==='intro');check(`${name}-confirm-once`,await page.evaluate(()=>window.__beginCalls===1));await page.evaluate(()=>window.__ember.useGame.setState({phase:'playing'}));await page.waitForTimeout(1000);
 await page.evaluate(()=>{const g=window.__ember.useGame;g.getState().speed(1);window.__originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('controlled denied storage','SecurityError');};g.getState().saveNow();});
 await page.waitForTimeout(6500);const banner=await page.evaluate(()=>({toast:window.__ember.useGame.getState().toast,error:window.__ember.useGame.getState().saveError,alert:[...document.querySelectorAll('[role="alert"]')].map(x=>x.textContent)}));check(`${name}-persistent-save-banner`,!!banner.error&&!banner.toast&&banner.alert.some(x=>x.includes('Retry save')),{...banner});await snap('save-denied');await page.evaluate(()=>{Storage.prototype.setItem=window.__originalSetItem;});await activate('Retry save');await page.waitForTimeout(300);check(`${name}-native-save-retry`,await page.evaluate(()=>window.__ember.useGame.getState().saveError===null)&&await page.getByRole('button',{name:'Retry save',exact:true}).count()===0);
 await page.evaluate(()=>window.__ember.useGame.getState().speed(0));
 // Native keyboard panel entry; no store command substitutes for Escape.
 await page.getByRole('button',{name:'You — pack, paperdoll, skills',exact:true}).click();await page.waitForTimeout(350);let inspect=page.getByRole('button',{name:/^Inspect /}).first();if(await inspect.isVisible().catch(()=>false)){
 await inspect.click();await page.waitForTimeout(100);const before=await page.locator('[data-tip-open="true"]').count();await page.keyboard.press('Escape');await page.waitForTimeout(200);const after=await page.locator('[data-tip-open="true"]').count();const still=await inspect.isVisible();await page.keyboard.press('Escape');check(`${name}-details-first-Escape`,before>0&&after===0&&still&&!await inspect.isVisible(),{before,after,panelAfterFirst:still});
 }else{check(`${name}-details-first-Escape`,false,{blocked:'i did not expose visible Inspect; see body evidence'});fs.writeFileSync(`${out}/${name}-body.txt`,await page.locator('body').innerText());await page.keyboard.press('Escape');}
 await snap('world');
 // Read-only R3F discovery for world point projection. No geometry/camera changes.
 const probe=await page.evaluate(()=>{const canvas=document.querySelector('canvas');const key=Object.keys(canvas).find(k=>k.startsWith('__reactFiber'));let f=canvas[key];for(let i=0;f&&i<30;i++,f=f.return){const stack=[f];let n=0;while(stack.length&&n++<3000){const q=stack.pop();if(q.memoizedProps?.store?.getState){const s=q.memoizedProps.store.getState();if(s.camera&&s.scene){window.__qaR3F=s;return {found:true,worldKeys:Object.keys(window.__ember.getWorld()),storeKeys:Object.keys(window.__ember.useGame.getState())};}}if(q.child)stack.push(q.child);if(q.sibling)stack.push(q.sibling);}}return {found:false};});fs.writeFileSync(`${out}/${name}-probe.json`,JSON.stringify(probe,null,2));
 if(mobile){const cdp=await context.newCDPSession(page);const x=viewport.width/2+60,y=viewport.height/2+40;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await page.waitForTimeout(700);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(200);const menu=await page.locator('body').innerText();fs.writeFileSync(`${out}/${name}-hold-body.txt`,menu);await snap('native-hold');check(`${name}-native-hold-dispatched`,true,{x,y,menuText:menu.slice(-1500),coverage:'unattributed target; not per-mesh PASS'});if(await page.getByRole('menu').count()){const target=await page.evaluate(()=>window.__ember.useGame.getState().ctx?.target);await page.setViewportSize({width:390,height:240});await page.waitForTimeout(300);const bounds=await page.getByRole('menu').boundingBox();await page.getByRole('menu').hover();await page.mouse.wheel(0,500);await page.waitForTimeout(150);const cancel=await page.getByRole('menuitem',{name:'Cancel',exact:true}).boundingBox();check(`${name}-native-menu-resize-scroll`,!!bounds&&bounds.x>=0&&bounds.y>=0&&bounds.x+bounds.width<=390&&bounds.y+bounds.height<=240&&!!cancel&&cancel.y+cancel.height<=240,{bounds,cancel,target});await page.getByRole('menuitem',{name:'Cancel',exact:true}).click();await page.setViewportSize(viewport);}await page.keyboard.press('Escape');}
 await page.evaluate(()=>{const w=window.__ember.getWorld();const p=w.people.find(q=>q.isPlayer);p.x=110;p.z=438;p.path=[];window.__ember.useGame.setState({panel:'none'});});await page.waitForTimeout(1500);await snap('underground-default');const pose=await page.evaluate(()=>({camera:window.__emberCamera?.getCamera(),target:window.__emberCamera?.getTarget(),effects:document.querySelector('[data-effects]')?.getAttribute('data-effects'),player:window.__ember.getWorld().people.filter(x=>x.isPlayer).map(x=>({x:x.x,z:x.z})),hour:window.__ember.getWorld().hour}));await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(350);await snap('underground-reduced');check(`${name}-underground-render-capture`,true,{fixture:'Player relocated to existing Greybarrow (110,438); no geometry/camera override; OS reduced-motion preference',pose,reduced:await page.locator('[data-effects]').first().getAttribute('data-effects')});
 }catch(e){check(`${name}-flow`,false,{error:String(e)});await snap('failure').catch(()=>{});}finally{await context.close();}}
}finally{await browser.close();flush();}
